### ISSUE TITLE
order of libraries

### ISSUE THREAD

**Issue by joprice** [OCamlPro/drom#174]
I am trying to use the `dune-libraries` property under `[fields]` to handle an issue where netsys is missing a dependency on `threads`:

https://github.com/ocaml/dune/issues/1024
https://gitlab.com/gerdstolpmann/lib-ocamlnet3/-/issues/14

I added threads to `package.toml`:

```toml
 [fields]
 dune-libraries = "threads"
```

but it ends up at the end of the list of dependencies, whereas I need it to show up before netsys. Editing the dune file to move it to the front of the list fixes this. Is there any way to work around this? Perhaps the packages could contain be objects that can contain a list of extra dependencies, which would then be used to topologically sort the libraries?

```toml
[[fields.dune-libraries.netsys]]
extra-deps = ["threads"]
```
