### ISSUE TITLE
Menhir handling

### ISSUE THREAD

**Issue by Ninjapouet** [OCamlPro/drom#199]
Following the PR https://github.com/OCamlPro/drom/pull/197, I suppose it would be nice to have a proper support to `menhir` as OCaml is often used DSL developments. I may suggest adding to  `package.toml` something like

```toml
[menhir]
version = "X.Y"
tokens = {filename = "<filename>"; flags = "<flags>"}
parser = {filename = "<filename>"; flags = "<flags>"}
```

which would toggle the `(use menhir "X.Y")` in `dune-project` and generate the `(menhir ...)` stanzas according to the PR recommandations.
